language: ruby
rvm:
  - 2.2.4

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "psql -c 'create database taekowndo_test;' -U postgres"
  - "RAILS_ENV=test bundle exec rake db:migrate"

script:
  - "RAILS_ENV=test bundle exec rspec"
