development:
  DEVELOPMENT_SECRET_KEY_BASE: 'your_development_secret_key_base'
  GOOGLE_CLIENT_ID: 'your_google_client_id'
  GOOGLE_CLIENT_SECRET: 'your_google_client_secret'

test:
  TEST_SECRET_KEY_BASE: 'your_test_secret_key_base'
  GOOGLE_CLIENT_ID: 'your_google_client_id'
  GOOGLE_CLIENT_SECRET: 'your_google_client_secret'

# This file will override above configurations
<%= IO.read('config/application.local.yml') if File.exists?('config/application.local.yml') %>
